<?php

$rj = json_decode('
    {
      "sigla": "RJ",
      "nome": "Rio de Janeiro",
      "cidades": [
        "Angra dos Reis",
        "Aperibé",
        "Araruama",
        "Areal",
        "Armação de Búzios",
        "Arraial do Cabo",
        "Barra do Piraí",
        "Barra Mansa",
        "Belford Roxo",
        "Bom Jardim",
        "Bom Jesus do Itabapoana",
        "Cabo Frio",
        "Cachoeiras de Macacu",
        "Cambuci",
        "Campos dos Goytacazes",
        "Cantagalo",
        "Carapebus",
        "Cardoso Moreira",
        "Carmo",
        "Casimiro de Abreu",
        "Comendador Levy Gasparian",
        "Conceição de Macabu",
        "Cordeiro",
        "Duas Barras",
        "Duque de Caxias",
        "Engenheiro Paulo de Frontin",
        "Guapimirim",
        "Iguaba Grande",
        "Itaboraí",
        "Itaguaí",
        "Italva",
        "Itaocara",
        "Itaperuna",
        "Itatiaia",
        "Japeri",
        "Laje do Muriaé",
        "Macaé",
        "Macuco",
        "Magé",
        "Mangaratiba",
        "Maricá",
        "Mendes",
        "Mesquita",
        "Miguel Pereira",
        "Miracema",
        "Natividade",
        "Nilópolis",
        "Niterói",
        "Nova Friburgo",
        "Nova Iguaçu",
        "Paracambi",
        "Paraíba do Sul",
        "Parati",
        "Paty do Alferes",
        "Petrópolis",
        "Pinheiral",
        "Piraí",
        "Porciúncula",
        "Porto Real",
        "Quatis",
        "Queimados",
        "Quissamã",
        "Resende",
        "Rio Bonito",
        "Rio Claro",
        "Rio das Flores",
        "Rio das Ostras",
        "Rio de Janeiro",
        "Santa Maria Madalena",
        "Santo Antônio de Pádua",
        "São Fidélis",
        "São Francisco de Itabapoana",
        "São Gonçalo",
        "São João da Barra",
        "São João de Meriti",
        "São José de Ubá",
        "São José do Vale do Rio Preto",
        "São Pedro da Aldeia",
        "São Sebastião do Alto",
        "Sapucaia",
        "Saquarema",
        "Seropédica",
        "Silva Jardim",
        "Sumidouro",
        "Tanguá",
        "Teresópolis",
        "Trajano de Morais",
        "Três Rios",
        "Valença",
        "Varre-Sai",
        "Vassouras",
        "Volta Redonda"
      ]
    }');

$lojas = json_decode('{
        "Saraiva 01" : {
            "rua" : "Rua Lauro Muller, 116",
            "bairro" : "Botafogo",
            "cidade" : "Rio de Janeiro",
            "estado" : "RJ"
        },
        "Saraiva 02" : {
            "rua" : "Praia de Botafogo, 400",
            "bairro" : "Botafogo",
            "cidade" : "Rio de Janeiro",
            "estado" : "RJ"
        },
        "Access Editora" : {
            "rua" : "Pinheiro Guimarães, 87",
            "bairro" : "Botafogo",
            "cidade" : "Rio de Janeiro",
            "estado" : "RJ"
        },
        "Prefácio" : {
            "rua" : "Rua Voluntários da Pátria, 39",
            "bairro" : "Botafogo",
            "cidade" : "Rio de Janeiro",
            "estado" : "RJ"
        },
        "A Outra" : {
            "rua" : "Rua Bambina, 39",
            "bairro" : "Botafogo",
            "cidade" : "Rio de Janeiro",
            "estado" : "RJ"
        },
        "Mais Uma" : {
            "rua" : "Praia de Botafogo, 39",
            "bairro" : "Botafogo",
            "cidade" : "Rio de Janeiro",
            "estado" : "RJ"
        }
    }');

$livros = json_decode('{
    "livros" : [
        "A Batalha do Apocalipse",
        "Filhos do Éden",
        "A Companhia Negra",
        "Lean Startup",
        "Eu Robô",
        "Sonhos de Robô",
        "Os Robôs",
        "A Fundação",
        "A Fundação e o Império",
        "A Segunda Fundação",
        "As Crônicas de Arthur",
        "A Busca do Graal",
        "Crônicas Saxônicas",
        "O Guia do Mochileiro das Galáxias"
    ]}');

